config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'


  resources :users, :except => :edit, :only => [] do
    collection do
      put :update
    end 
  end
  
  resources :volunteers, :only => [:show,:index] do
    collection do
      get :edit
    end
  end


  resources :ngo, :only => [] do
    collection do
      get :edit
    end
  end 

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :users
end

app/models/ngo.rb
class Ngo < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # geocoded_by :location   # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates



  validates :first_name, :presence => true
  validates :last_name, :presence => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :country

  # def location
  #   location = "#{country.name},#{:city}"
  #   location
  # end
end

app/models/volunteer.rb
class Volunteer < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :type, :email, :password)}
  end
end

app/controllers/ngo_controller.rb
class NgoController < UsersController
  before_action :authenticate_user!
  
  def edit
    @ngo = current_user
  end

  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def show
    
  end

  def edit
    

  end

  def update

    @user = current_user
    @user.update(allowed_params)
  end

  def allowed_params #whitelist
    params.require(:user).permit(:first_name, :country,:city,:last_name, :email, :mobile) #for each attribute in the model /white_listed
  end  

end

app/controllers/volunteers_controller.rb
class VolunteersController < UsersController
  

  def index
    @users = Volunteer.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @volunteer = current_user
    @countries = Country.all
    @countries = @countries.map{ |country|
      ["#{country[:name]}",country[:id]]
    }
  end

  def allowed_params #whitelist
    params.require(:user).permit(:skype,:role,:relevant_exp,:work_remote,:travel_expenses,:country,:city,:username, :password, :password_confirmation, :current_password)#for each attribute in the model /white_listed
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ngo_helper.rb
module NgoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Step Up Connecting Volunteers and NGOS</title>
<!-- Bootstrap core CSS -->
  <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="http://getbootstrap.com/examples/jumbotron/jumbotron.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,700' rel='stylesheet' type='text/css'>
  <!-- MAP JAVASCRIPT -->
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBa6pCZqs-padkcoNkzOOGtkMdjDp8NtRc">
  </script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <$= stylesheet_link_tag 'main'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body cz-shortcut-listen="true">
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
    <!--   <%= link_to "Step Up Connecting Volunteers and NGOS",'/',:class =>"navbar-brand"%> -->
      <div class = "navbar-brand">
        <div class ="text"
          <p id = "step">Step Up</p> 
          <p id = "connecting">Connecting Volunteers and NGOS</p>
       </div>
      </div>
      </div>
      <div class="navbar-collapse collapse">

      <ul class="nav navbar-nav  navbar-right">
        <li><%=link_to 'Volunteers',volunteers_path %></li>
        <li class="active"><%= link_to "Register",new_user_registration_path %></li>
        <li><%=link_to 'Sign in',user_session_path %></li>
      </ul>
 
      </div><!--/.navbar-collapse -->
    </div>
  </div>

<% if notice %>
<p class="alert alert-warning fade in"><%= notice %></p>
<% end %>
<% if alert  %>
<p class="alert alert-success"><%= alert %></p>
<% end %>
<%= yield %>


<footer>
  <p class = "footer-text">#stepupsvc</o>
</footer>
</div> 


<!-- Bootstrap core JavaScript -->
<!-- <script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script> -->


</body>
</html>

app/views/ngo/edit.html.erb
<h1>Ngo#edit</h1>
<p>Find me in app/views/ngo/edit.html.erb</p>

app/views/pages/home.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" id="map-canvas" data-volunteers="<%= Volunteer.all.to_json%>">

    </div>

    <div class = "options">
    <div class="container options">
      <!-- Example row of columns -->
      <div class = "type">
      <div class="row options text-center">
        <div class="col-md-4">
          <h2 class = "categories">Volunteers</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
          <h2 class ="categories">Ngos</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
       </div>
        <div class="col-md-4">
          <h2 class = "categories">More Info</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/jumbotron/#" role="button">View details »</a></p>
        </div>
      </div>
    </div>

    </div>
   

app/views/users/show.html.erb
<h1>Volunteer Profile Page</h1>

<h3><%= @user.first_name %><%= @user.last_name %></h3>

<ul>
  <li>Email: <%= @user.email %></li>
  <li>Mobile: <%= @user.mobile %></li>
  <li>Skype: <%= @user.skype %></li>
  <li>Role: <%= @user.role %></li>
  <li>Relevant Experience: <%= @user.relevant_experience %></li>
  <li>Can you work Remote? <%= @user.work_remote %></li>
  <li>Can you cover your travel expenses? <%= @user.travel_experience %></li> 
</ul>

app/views/volunteers/edit.html.erb
<div class = "container">
<div class="edit-profile">
<h1>Edit profile</h1>

<%= form_for @volunteer, as: :user, url: users_path,:method => :put,html: {class: "smart-green"} do |f| %>

  <%= field_set_tag do %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :email %>
    <%= f.text_field :email %>
  <% end %>

  <%= field_set_tag do %>
  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %></div>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :country %>
    <%= f.select :country_id, :options => @countries%>
 

  <% end %>

  <%= field_set_tag do %>
    <%= f.label :city %>
    <%= f.text_field :city_id %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :skype %>
    <%= f.text_field :skype %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :role %>
    <%= f.text_field :role %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :relevant_exp %>
    <%= f.text_area(:relevant_exp, :cols => 50, :rows => 20, :class => "experience") %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :work_remote %>
    <%= f.text_field :work_remote %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :travel_expenses %>
    <%= f.text_field :travel_expenses %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label "Have you received training in relevant courses?" %>
    <%= f.text_field :training %>
  <% end %>

<%= submit_tag "Update"%> 

<% end %>

</div>
</div>

app/views/volunteers/index.html.erb
<div class = "container">
  <% @users.each do |user| %>

  <h1><%=link_to "#{user.first_name} #{user.last_name}",volunteer_path(user) %></h1>

  <% end %>
</div>

app/views/volunteers/show.html.erb
<div class = "container">
  <div class = "row"> 
    <div class = "col-md-6">
      <%= "#{@user.first_name} #{@user.last_name}" %>
    </div>
  </div>
  <div class = "row">
    <div class = "row"> 
    <div class = "col-md-6">
      <%= @user.role%>
    </div>
    </div>
    <div class = "row"> 
    <div class = "col-md-6">
      <%= @user.relevant_exp %>
    </div>
  </div>
    <div class = "row"> 
    <div class = "col-md-6">
      <%= @user.training %>
    </div>
  </div>
    <div class = "row"> 
    <div class = "col-md-6">
      <% if @user.work_remote && @user.work_remote == "1" %>
          yes
      <% else %>
          no
      <% end %>
    </div>
  </div>
    <div class = "row"> 
    <div class = "col-md-6">
      <% if @user.travel_expenses && @user.travel_expenses == "1" %>
          yes
      <% else %>
          no
      <% end %>
    </div>
  </div>

  <div class = "row"> 
    <div class = "col-md-6">
      <%= @user.country.name %>
    </div>
  </div>

  <div class="col-md-6 user-map" id="map-canvas" data-volunteers="<%= Volunteer.all.to_json%>">

  </div>
</div>
</div>


 "first_name"
    t.string   "last_name"
    t.string   "mobile"
    t.string   "skype"
    t.string   "role"
    t.string   "relevant_exp"
    t.boolean  "work_remote"
    t.boolean  "travel_expenses"
    t.string   "type"
    t.string   "training"
    t.integer  "country_id"
    t.integer  "city_id"
       t.string   "email",   